### ISSUE TITLE
ES2ESC and ES2BLE I/O Ports

### ISSUE THREAD

**Issue by VictorCasadoZ** [etransport/ninebot-docs#4]
Dear etransport,

Could you please upload the I/O Ports specifications of the ES2ESC and ES2BLE boards, as you did with the M365 ones?

Thank you so much!

**Comment by flowswitch** [comment]
Added ES2 ESC I/O table (I had this info ready), BLE will require some time.

**Comment by VictorCasadoZ** [comment]
Hi,
I have been testing it and I think that it doesn't match the pinout of my board, in my board it sais NINEBOT ESC2-L-Driver ReV_2.1, it is a blue board.

Thank you

**Comment by truesurge** [comment]
> Hi,
> I have been testing it and I think that it doesn't match the pinout of my board, in my board it sais NINEBOT ESC2-L-Driver ReV_2.1, it is a blue board.
> 
> Thank you

We dont support any scooter-sharing hardware. Please, return it to original owner
